#
# @desc Minimal kitty configuration file
# @auth jaborvs
#

### Fonts ######################################################################
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10

### Window Layout ##############################################################
# Adds a nice internal gap so text doesn't touch the Sway borders
window_padding_width 10

# Tells Kitty not to draw its own titlebar (Sway handles this)
hide_window_decorations yes
confirm_os_window_close 0

### Behavior & Interaction #####################################################
enable_audio_bell no
copy_on_select yes

### Color Scheme ###############################################################
background #101010
foreground #f6f1ea

# Cursor colors
cursor            #afa193
cursor_text_color #101010

# Selection colors
selection_background #afa193
selection_foreground #101010

# The 16 terminal colors
color0 #101010
color8 #333333

color1 #cc6666
color9 #d17b7b

color2  #a9b665
color10 #b4c170

color3  #d8a657
color11 #e1b56d

color4  #7daea3
color12 #8bbaaf

color5  #d3869b
color13 #dc97ab

color6  #89b482
color14 #98c391

color7  #afa193
color15 #f6f1ea
