#
# @desc Minimal kitty configuration file
# @auth jaborvs
#

### Fonts ######################################################################
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10

### Window Layout ##############################################################
# Adds a nice internal gap so text doesn't touch the Sway borders
window_padding_width 10

# Tells Kitty not to draw its own titlebar (Sway handles this)
hide_window_decorations yes
confirm_os_window_close 0

### Behavior & Interaction #####################################################
enable_audio_bell no
copy_on_select yes

# Config for nvim
allow_remote_control yes
listen_on unix:/tmp/mykitty

### Color Scheme ###############################################################

# The basic colors
foreground              #CECDC3
background              #100F0F
selection_foreground    #100F0F
selection_background    #CECDC3

# Cursor colors
cursor                  #CECDC3
cursor_text_color       #100F0F

# URL underline color when hovering with mouse
url_color               #24837B

# Kitty window border colors
active_border_color     #403E3C
inactive_border_color   #282726

# Tab bar colors
active_tab_foreground   #CECDC3
active_tab_background   #282726
inactive_tab_foreground #878580
inactive_tab_background #1C1B1A

# The 16 terminal colors

# black
color0 #100F0F
color8 #575653

# red
color1 #AF3029
color9 #D14D41

# green
color2  #66800B
color10 #879A39

# yellow
color3  #AD8301
color11 #D0A215

# blue
color4  #205EA6
color12 #4385BE

# magenta
color5  #A02F6F
color13 #CE5D97

# cyan
color6  #24837B
color14 #3AA99F

# white
color7  #CECDC3
color15 #FFFCF0
