#
# @desc Minimal kitty configuration file
# @auth jaborvs
#

### Fonts ######################################################################
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10

### Window & Aesthetics ########################################################
window_padding_width     10
hide_window_decorations  yes
background_opacity       1

### Tabs #######################################################################
tab_bar_style powerline

### Behavior & Interaction #####################################################
scrollback_lines          10000
enable_audio_bell         no
cursor_shape              block
cursor_blink_interval     0
confirm_os_window_close   0

### Colors #####################################################################
background           #1d1f21
foreground           #c5c8c6
selection_background #373b41
selection_foreground #c5c8c6
